<#
  build-bt-sample-seed.ps1 · bt-bridge-v1

  Turns an Outlook CSV export of the Buildertrend folder into a SQL seed that loads
  every row into bt_emails (the insert trigger parses each one). Default input is
  samples/Samples.CSV; pass -Csv for a fresh export. This is the manual bridge until
  live ingest is running: export the folder, run this, run the SQL.

  Outlook's CSV export has no Message-ID and no date, so the seed synthesises a stable
  id from a SHA-1 of subject + body ('csv:<hash>'). Re-running the seed is a no-op for
  rows already loaded (ON CONFLICT DO NOTHING on message_id).

  Usage (from the repo root):
    powershell -ExecutionPolicy Bypass -File tools\build-bt-sample-seed.ps1
    powershell -ExecutionPolicy Bypass -File tools\build-bt-sample-seed.ps1 -Csv samples\Buildertrend-2026-09-14.CSV -Out supabase\seed\bt_2026-09-14.sql
#>
param([string]$Csv, [string]$Out)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$csv  = if ($Csv) { (Resolve-Path $Csv).Path } else { Join-Path $root 'samples\Samples.CSV' }
$out  = if ($Out) { (Join-Path (Get-Location) $Out) } else { Join-Path $root 'supabase\seed\bt_samples.sql' }

if (-not (Test-Path $csv)) { throw "Missing $csv" }
New-Item -ItemType Directory -Force (Split-Path -Parent $out) | Out-Null

$rows = Import-Csv $csv -Encoding UTF8
$sha  = [System.Security.Cryptography.SHA1]::Create()
$utf8 = New-Object System.Text.UTF8Encoding($false)

# Dollar-quote with a tag that cannot appear in an email body.
$tag = '$bt$'
function Q([string]$s) { if ($null -eq $s) { return 'null' }; return "$tag$s$tag" }

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("-- Generated by tools/build-bt-sample-seed.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm') from $(Split-Path -Leaf $csv) ($($rows.Count) rows).")
[void]$sb.AppendLine("-- Loads raw sample emails into bt_emails; the insert trigger parses each one.")
[void]$sb.AppendLine("-- Safe to re-run. Then:  select event_type, count(*) from bt_events group by 1 order by 2 desc;")
[void]$sb.AppendLine("begin;")

$n = 0
foreach ($r in $rows) {
  $subject = [string]$r.Subject
  $body    = [string]$r.Body
  if ([string]::IsNullOrWhiteSpace($subject) -and [string]::IsNullOrWhiteSpace($body)) { continue }
  $hash = ($sha.ComputeHash($utf8.GetBytes($subject + "`n" + $body)) | ForEach-Object { $_.ToString('x2') }) -join ''
  $mid  = "csv:$hash"
  $from = [string]$r.'From: (Address)'
  $fromName = [string]$r.'From: (Name)'
  $to   = [string]$r.'To: (Address)'
  if ($to.Length -gt 300) { $to = $to.Substring(0, 300) }   # X500 recipient strings can be huge; not needed for parsing

  [void]$sb.AppendLine("insert into bt_emails (message_id, from_address, from_name, to_address, subject, body_text, source) values (")
  [void]$sb.AppendLine("  $(Q $mid), $(Q $from.ToLower()), $(Q $fromName), $(Q $to),")
  [void]$sb.AppendLine("  $(Q $subject),")
  [void]$sb.AppendLine("  $(Q $body),")
  [void]$sb.AppendLine("  'csv_import') on conflict (message_id) do nothing;")
  $n++
}
[void]$sb.AppendLine("commit;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("-- Expected on the 2026-09-14 sample set (64 rows, 28 notifications):")
[void]$sb.AppendLine("--   client_update 19 · change_order_added 3 · change_order_approved 3 · document_comment 2 · change_order_file 1 · unclassified 36")
[void]$sb.AppendLine("select event_type, count(*) from bt_events group by 1 order by 2 desc;")

[IO.File]::WriteAllText($out, $sb.ToString(), $utf8)
Write-Host "Wrote $n rows to $out"
